substitutions:
  ## Avoid underscores, since ESPHome uses mDNS, underscores can be funny with mDNS and there is no inbuilt sanitiser.
  name: "ag-one"
  friendly_name: "AirGradient One"
  room: ""
  device_description: "AirGradient Air Monitor with OLED Display & LEDs" 
  project_name: "AirGradient.AG One"
  project_version: "2.5.0"
  ## Define a domain for this device to use. i.e. iot.home.lan (so device will appear as device.iot.home.lan in DNS/DHCP logs)
  dns_domain: ".local"
  ## Set timezone of the device. Can be entered in unix Country/Area format (i.e. "Australia/Sydney")
  timezone: "Australia/Sydney"
  ## Enables faster network connections, with last connected SSID being connected to and no full scan for SSID being undertaken
  wifi_fast_connect: "true"
  
  ## Offset for SenseAir C02 Sensor
  co2_offset: '0'
  ## Time the PMS500x spends idle/off to preserve the laser - https://esphome.io/components/sensor/pmsx003.html
  pm_update_interval: "300s"
  ## Interval for all non PMSX003 sensors to update (diagnostic sensors not included)
  sensor_update_interval: 60s

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  area: "${room}"
  name_add_mac_suffix: false
  min_version: 2024.11.0
  project:
    name: "${project_name}"
    version: "${project_version}"

esp32:
  ## https://esphome.io/components/esp32.html
  board: esp32-c3-devkitm-1
  framework: 
    type: esp-idf

preferences:
  flash_write_interval: 15min

api:
  encryption: 
    ## EPSHome & HA seem to whinge if there is no encryption.
    key: !secret api_key
ota:
  - platform: esphome
    password: !secret ota_password

logger:
  baud_rate: 0
  level: ERROR

wifi:
  ## https://esphome.io/components/wifi/
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: "${wifi_fast_connect}"
  domain: "${dns_domain}"
  ## Manual IP Template; Suggested to use when you have a busy wireless network to prevent HA making errors
  # manual_ip: 
  #   static_ip: x.x.x.x
  #   gateway: x.x.x.x
  #   subnet: 255.255.255.0

uart:
  ## https://esphome.io/components/uart.html#uart
  - rx_pin: GPIO0  # Pin 12
    tx_pin: GPIO1  # Pin 13
    baud_rate: 9600
    id: senseair_s8_uart

  - rx_pin: GPIO20  # Pin 30 or RX
    tx_pin: GPIO21  # Pin 31 or TX
    baud_rate: 9600
    id: pms5003_uart

i2c:
  ## https://esphome.io/components/i2c.html
  sda: GPIO7 # Pin 21
  scl: GPIO6 # Pin 20
  frequency: 400kHz  # 400kHz eliminates warnings about components taking a long time other than SGP40 component: https://github.com/esphome/issues/issues/4717

sensor:
  - platform: pmsx003
    ## PMS5003 https://esphome.io/components/sensor/pmsx003.html
    type: PMSX003
    uart_id: pms5003_uart
    pm_2_5:
      name: "${friendly_name} PM 2.5"
      id: pm_2_5
      ## Added to report properly to HomeKit
      device_class: pm25
    pm_1_0:
      name: "${friendly_name} PM 1.0"
      id: pm_1_0
      ## Added to report properly to HomeKit
      device_class: pm1  
    pm_10_0:
      name: "${friendly_name} PM 10.0"
      id: pm_10_0
      ## Added to report properly to HomeKit
      device_class: pm10  
    pm_0_3um:
      name: "${friendly_name} PM 0.3"
      id: pm_0_3um
      ## Update the AQI sensor every time we collect a new PMx reading
      on_value: 
        then:
          - component.update: pm_2_5_aqi
    update_interval: $pm_update_interval
  
  - platform: template
    ## Depends on another sensor providing an ID of pm_2_5 such as a pms5003
    name: "${friendly_name} PM 2.5 AQI"
    id: pm_2_5_aqi
    update_interval: never
    unit_of_measurement: "AQI"
    icon: "mdi:air-filter"
    accuracy_decimals: 0
    filters:
      ## Need valid data from PM 2.5 sensor before able to calculate
      - skip_initial: 3  
    lambda: |-
      // https://en.wikipedia.org/wiki/Air_quality_index#Computing_the_AQI
      // Borrowed from https://github.com/kylemanna/sniffer/blob/master/esphome/sniffer_common.yaml
      if (id(pm_2_5).state <= 12.0) {
      // good
      return((50.0 - 0.0) / (12.0 - 0.0) * (id(pm_2_5).state - 0.0) + 0.0);
      } else if (id(pm_2_5).state <= 35.4) {
      // moderate
      return((100.0 - 51.0) / (35.4 - 12.1) * (id(pm_2_5).state - 12.1) + 51.0);
      } else if (id(pm_2_5).state <= 55.4) {
      // usg
      return((150.0 - 101.0) / (55.4 - 35.5) * (id(pm_2_5).state - 35.5) + 101.0);
      } else if (id(pm_2_5).state <= 150.4) {
      // unhealthy
      return((200.0 - 151.0) / (150.4 - 55.5) * (id(pm_2_5).state - 55.5) + 151.0);
      } else if (id(pm_2_5).state <= 250.4) {
      // very unhealthy
      return((300.0 - 201.0) / (250.4 - 150.5) * (id(pm_2_5).state - 150.5) + 201.0);
      } else if (id(pm_2_5).state <= 350.4) {
      // hazardous
      return((400.0 - 301.0) / (350.4 - 250.5) * (id(pm_2_5).state - 250.5) + 301.0);
      } else if (id(pm_2_5).state <= 500.4) {
      // hazardous 2
      return((500.0 - 401.0) / (500.4 - 350.5) * (id(pm_2_5).state - 350.5) + 401.0);
      } else {
      return(500);
      }

  - platform: senseair
    ## https://esphome.io/components/sensor/senseair.html
    co2:
      name: "${friendly_name} CO2"
      id: co2
      filters:
        - offset: $co2_offset
    id: senseair_s8
    uart_id: senseair_s8_uart
    update_interval: $sensor_update_interval

  - platform: sht4x
    ## https://esphome.io/components/sensor/sht4x.html
    temperature:
      name: "${friendly_name} Temperature"
      id: temp
    humidity:
      name: "${friendly_name} Humidity"
      id: humidity
    # heater_max_duty: 0.05
    address: 0x44
    update_interval: $sensor_update_interval

  - platform: sgp4x
    ## https://esphome.io/components/sensor/sgp4x.html
    voc:
      name: "${friendly_name} VOC Index"
      id: voc
    nox:
      name: "${friendly_name} NOx Index"
      id: nox
    ## Remove this block if no temp/humidity sensor present for compensation
    compensation:  
      temperature_source: temp
      humidity_source: humidity
    address: 0x59
    update_interval: $sensor_update_interval

  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic

  ## https://esphome.io/components/sensor/uptime.html
  - platform: uptime
    id: uptime_sec
    internal: true
    on_value_range: 
      - above: 30
        then:
          - display.page.show: summary
      - below: 60
        then: 
          - display.page.show: boot

  - platform: template
    id: uptime_timestamp
    name: "${friendly_name} Uptime"
    device_class: timestamp
    entity_category: diagnostic
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
      static float timestamp = (
        id(current_time).utcnow().timestamp - id(uptime_sec).state
      );
      return timestamp;

binary_sensor:
  ## https://esphome.io/components/binary_sensor/status.html
  - platform: status
    name: "${friendly_name} Status"
    entity_category: diagnostic

  - platform: gpio
    ## Binary sensor to perform action when physical config button is pressed
    ## https://esphome.io/components/binary_sensor/index.html?highlight=on_multi_click
    name: "${friendly_name} Hardware Button"
    id: hardware_button
    internal: true
    pin:
      number: GPIO9
      mode: INPUT_PULLUP
      inverted: true
      ignore_strapping_warning: true
    on_multi_click:
      ## Short Press
      - timing:  
          - ON for at most 1s
          - OFF for at least 0.5s
        then:
          - button.press: s8_calibrate_button
      ## Long Press
      # - timing:  
      #     - ON for 1s to 5s
      #     - OFF for at least 0.5s
      #   then:
      #     - 

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      icon: "mdi:ip"
      entity_category: diagnostic
    ssid:
      name: "${friendly_name} Connected SSID"
      icon: "mdi:network"
      entity_category: diagnostic
    mac_address:
      name: "${friendly_name} Mac Address"
      entity_category: diagnostic

  ## Creates a sensor showing when the device was last restarted
  - platform: template
    name: "${friendly_name} Last Reboot"
    id: last_reboot
    icon: mdi:clock
    entity_category: diagnostic

button:
  ## https://github.com/esphome/issues/issues/2444
  - platform: template
    name: S8 Calibration
    id: s8_calibrate_button
    on_press:
      then:
          - logger.log: "Starting Manual CO2 Calibration"
          - senseair.background_calibration: senseair_s8
          - delay: 70s
          - senseair.background_calibration_result: senseair_s8
          - logger.log: "Finished Manual CO2 Calibration"

  - platform: template
    ## Displays the current ABC interval in the ESPhome logs to verify status
    name: "${friendly_name} S8 Print Calibration Interval"
    id: s8_print_calibration
    entity_category: diagnostic
    on_press:
      then:
        - senseair.abc_get_period: senseair_s8

  - platform: restart
    name: "${friendly_name} Restart"
    entity_category: config
    device_class: restart
    icon: "mdi:restart"
  - platform: factory_reset
    name: "${friendly_name} Factory Reset"
    id: Reset
    entity_category: config
    icon: "mdi:restore"
  - platform: safe_mode
    name: "${friendly_name} Safe Mode"
    entity_category: config
    on_press:
      logger.log: "Entering Safe Mode..."
    icon: "mdi:restart-alert"

switch:
  - platform: template
    name: "${friendly_name} S8 Automatic Baseline Correction"
    id: s8_abc_switch
    icon: "mdi:auto-mode"
    restore_mode: RESTORE_DEFAULT_ON
    optimistic: True
    entity_category: config
    turn_on_action:
      - senseair.abc_enable: senseair_s8
    turn_off_action:
      - senseair.abc_disable: senseair_s8

number:
  - platform: template
    ## https://esphome.io/components/number/template.html
    name: "${friendly_name} Display Contrast %"
    icon: "mdi:contrast-circle"
    id: display_contrast
    min_value: 0
    max_value: 100
    step: 1
    initial_value: 100
    optimistic: true
    restore_value: true
    mode: slider
    on_value:
      then:
        ## https://www.reddit.com/r/Esphome/comments/sy1d1s/how_to_write_a_lamba_to_change_the_contrast_of/
        lambda: id(oled_display).set_contrast(id(display_contrast).state / 100.0);

  - platform: template
    name: "${friendly_name} LED Brightness %"
    icon: "mdi:brightness-percent"
    id: led_brightness
    min_value: 0
    max_value: 100
    step: 1
    initial_value: 100
    optimistic: true
    restore_value: true
    mode: slider

  - platform: template
    name: "${friendly_name} LED Fade %"
    icon: "mdi:shimmer"
    id: led_fade
    min_value: 0
    max_value: 100
    step: 1
    initial_value: 20
    optimistic: true
    restore_value: true
    mode: box

display:
  - platform: ssd1306_i2c
    ## https://esphome.io/components/display/ssd1306.html
    ## Formatting reference: https://www.tutorialspoint.com/c_standard_library/c_function_printf.htm
    model: "SH1106 128x64"
    id: oled_display
    address: 0x3C
    # rotation: 180°
    pages:
      - id: summary
        ## https://forum.airgradient.com/t/airgradient-one-customized-mallocarray-esphome-display/1328
        lambda: |-
          it.printf(0, 0, id(open_sans_14), "%.1f°C", id(temp).state);
          it.printf(128, 0, id(open_sans_14), TextAlign::TOP_RIGHT, "%.1f%%", id(humidity).state);
          it.line(0,17,128,17);
          it.printf(16,19, id(open_sans_9), "CO2");
          it.printf(0,27, id(open_sans_20), "%.0f", id(co2).state);
          it.printf(0,52, id(open_sans_9), "ppm");
          it.line(50,19,50,64);
          it.printf(62, 19, id(open_sans_9), "PM2.5");
          it.printf(54, 27, id(open_sans_20), "%.0f", id(pm_2_5).state);
          it.printf(54, 52, id(open_sans_9), "µg/m³");
          it.line(100,19,100,64);
          it.printf(104,18, id(open_sans_9), "TVOC");
          it.printf(104,29, id(open_sans_9), "%.0f", id(voc).state);
          it.printf(104,41, id(open_sans_9), "NOx");
          it.printf(104,52, id(open_sans_9), "%.0f", id(nox).state);
      - id: boot
        lambda: |-
          it.printf(0, 0, id(open_sans_14), "ID:");
          it.printf(128, 0, id(open_sans_14), TextAlign::TOP_RIGHT, "%s", get_mac_address().c_str());
          it.printf(0, 21, id(open_sans_14), "Config Ver: ${project_version}");
          it.printf(0, 42, id(open_sans_14), "${friendly_name}");

light:
  ## https://esphome.io/components/light/esp32_rmt_led_strip.html
  - platform: esp32_rmt_led_strip
    name: "${friendly_name} LED Strip"
    id: led_strip
    rgb_order: GRB
    pin: GPIO10  # Pin 16
    num_leds: 11
    chipset: ws2812
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - platform: gpio
    ## Pin to notify external watchdog that activity is present
    id: watchdog
    pin:
      number: GPIO2
      ## Acknowledging that this is a strapping pin and should not have external pullup/down resistors  https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
      ignore_strapping_warning: true  

time:
  - platform: homeassistant
    id: current_time
    timezone: "${timezone}"
    # update_interval: 24hours
    on_time_sync:
      then:
        - component.update: uptime_timestamp
        - logger.log: "Synchronized System Clock"
        ## Update last restart time, but only once.
        - if:
            condition:
              lambda: 'return id(last_reboot).state == "";'
            then:
              - text_sensor.template.publish:
                  id: last_reboot
                  state: !lambda 'return id(current_time).now().strftime("%d/%m/%y - %H:%M:%S");'
              - logger.log: "set 'last_reboot' time"

interval:
  - interval: 2.5min
    ## Notify watchdog device it is still alive
    then:
      - output.turn_on: watchdog
      - delay: 20ms
      - output.turn_off: watchdog

font:
  - file: "gfonts://Open Sans"
    id: open_sans_14
    size: 14
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/µ³'
  - file: "gfonts://Open Sans"
    id: open_sans_9
    size: 9
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/µ³'
  - file: "gfonts://Open Sans"
    id: open_sans_20
    size: 20
    glyphs: '!"%()+=,-_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz/µ³'
